### PR TITLE
osx-arm64 + aarch64 + version bump

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @martinRenou @conda-forge/gazebo - this package is a dependency of gazebo. It currently does not have a run_exports directive, we should probably add it. Any idea whether it should be on the minor or patch version? Any do you foresee issues bumping the version?

**Comment by Tobias-Fischer** [comment]
Fix #1 #2

**Comment by Tobias-Fischer** [comment]
Otherwise I think this is ready for review / merge :)

**Comment by martinRenou** [comment]
Thanks! Do you want to add yourself in the maintainers list?

**Comment by Tobias-Fischer** [comment]
Sure.

**Comment by traversaro** [comment]
> Any idea whether it should be on the minor or patch version? Any do you foresee issues bumping the version?

Up to 1.20.1 release it seems quite good backcompatible: https://abi-laboratory.pro/index.php?view=timeline&l=openal . Probably a good compromise is to have run_exports on minor version?

**Comment by Tobias-Fischer** [comment]
Thanks @traversaro

**Comment by Tobias-Fischer** [comment]
This is ready to go now @martinRenou

**Comment by martinRenou** [comment]
Thanks!

**Pull request merged**
